=== shanjit/cis550---Pennterest/export/pennterest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="pennterest" type="pinsiteType">
	    <xs:key name="objId">
	      <xs:selector xpath="object"/>
	      <xs:field xpath="id"/>
	      <xs:field xpath="source"/>
	    </xs:key>
	    <xs:key name="userId">
	      <xs:selector xpath="user"/>
	      <xs:field xpath="login"/>
	    </xs:key>
      <xs:keyref name="friendRef" refer="userId">
      	<xs:selector xpath="user/friend"/>
      	<xs:field xpath="."/>
      </xs:keyref>
      <xs:keyref name="pinObjectRef" refer="objId">
      	<xs:selector xpath="user/pin"/>
      	<xs:field xpath="objectId"/>
        <xs:field xpath="sourceId"/>
      </xs:keyref>
    </xs:element>

	<xs:simpleType name="objectClass">
	  <xs:restriction base="xs:string">
	    <xs:enumeration value="photo" />
	    <xs:enumeration value="pdf" />
	    <xs:enumeration value="video" />
	  </xs:restriction>
	</xs:simpleType>    
	
    <xs:complexType name="pinsiteType">
    	<xs:sequence>
    		<!--  The group or owner of the Pinterest site -->
    		<xs:element name="operator" type="xs:string"></xs:element>
    		<!-- URL of your Pinterest clone -->
    		<xs:element name="web_url" type="xs:string"></xs:element>
    		<!-- The things to be pinned / rated -->
    		<xs:element name="object" type="objType" minOccurs="0" maxOccurs="unbounded"></xs:element>
    		<xs:element name="user" type="userType" minOccurs="0" maxOccurs="unbounded">
    		<!--  these keys and keyrefs are relative to the user, i.e., board is unique to user -->
			    <xs:key name="boardId">
			      <xs:selector xpath="board"/>
			      <xs:field xpath="name"/>
			    </xs:key>
		      <xs:keyref name="pinBoardRef" refer="boardId">
		      	<xs:selector xpath="pin"/>
		      	<xs:field xpath="board"/>
		      </xs:keyref>
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="objType">
    	<xs:sequence>
    		<!-- Object ID as assigned by the project group -->
    		<xs:element name="id" type="xs:integer"></xs:element>
    		<!-- The origin of the object, i.e., the name of the Project Group that supplied it -->
    		<xs:element name="source" type="xs:string"></xs:element>
    		<!--  photo, PDF, etc -->
    		<xs:element name="type" type="objectClass"></xs:element>
    		<!-- Original group -->
    		<xs:element name="url" type="xs:string"></xs:element>
    		<xs:element name="tag" type="xs:string" minOccurs="0" maxOccurs="unbounded"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="userType">
      <xs:sequence>
        <xs:element name="login" type="xs:string"></xs:element>
        <xs:element name="email" type="xs:string"></xs:element>
        <xs:element name="givenname" type="xs:string"></xs:element>
        <xs:element name="surname" type="xs:string"></xs:element>
        <xs:element name="affiliation" type="xs:string"></xs:element>
        <xs:element name="birthday" type="xs:date"></xs:element>
        <xs:element name="interests" type="xs:string" minOccurs="0" maxOccurs="unbounded"></xs:element>
        <xs:element name="friend" type="xs:string" minOccurs="0" maxOccurs="unbounded"></xs:element>
        <xs:element name="board" type="boardType" maxOccurs="unbounded"></xs:element>
        <xs:element name="pin" type="pinType" minOccurs="0" maxOccurs="unbounded"></xs:element>
        <xs:element name="rating" type="ratingType" minOccurs="0" maxOccurs="unbounded"></xs:element>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="boardType">
      <xs:sequence>
      	<!--  Board name should be unique per user -->
        <xs:element name="name" type="xs:string"></xs:element>
        <!--  can optionally define a type of board -->
        <xs:element name="type" type="xs:string" minOccurs="0"></xs:element>
      </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="pinType">
      <xs:sequence>
      	<!--  Reference to the object being pinned -->
   		<xs:element name="objectId" type="xs:integer"></xs:element>
   		<!--  Reference to the object's creating group / source -->
   		<xs:element name="sourceId" type="xs:string"></xs:element>
   		<!--  changed from the last homework: let's make pins associated with ONLY the user's
   		board -->
   		<xs:element name="board" type="xs:string"></xs:element>
      </xs:sequence>
    </xs:complexType>
    <!--  Separated from pinning, as per discussion -->
    <xs:complexType name="ratingType">
      <xs:sequence>
      	<!--  Reference to the object being pinned -->
   		<xs:element name="objectId" type="xs:integer"></xs:element>
   		<!--  Reference to the object's creating group / source -->
   		<xs:element name="sourceId" type="xs:string"></xs:element>
   		<xs:element name="rating" type="xs:integer"></xs:element>
      </xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== shanjit/cis550---Pennterest/export/ours.xml
<?xml version="1.0" encoding="UTF-8"?>
<pennterest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pennterest.xsd">
  <operator>Group TBD</operator>
  <web_url>www.shanjoshandreimainak.com</web_url>
  <object>
    <id>1</id>
    <source>TBD</source>
    <type>photo</type>
    <url>http://www.dartfrogforums.com/images/tinc_540x350_1.jpg</url>
    <tag>animals</tag>
  </object>
  <object>
    <id>2</id>
    <source>TBD</source>
    <type>photo</type>
    <url>http://images2.fanpop.com/images/photos/6900000/Felines-national-geographic-6909274-1024-768.jpg</url>
    <tag>animals</tag>
  </object>
  <object>
    <id>3</id>
    <source>TBD</source>
    <type>photo</type>
    <url>http://eofdreams.com/data_images/dreams/tiger/tiger-02.jpg</url>
    <tag>animals</tag>
  </object>
  <object>
    <id>4</id>
    <source>TBD</source>
    <type>photo</type>
    <url>http://images.nationalgeographic.com/wpf/media-live/photos/000/004/cache/african-lion-male_436_600x450.jpg</url>
    <tag>animals</tag>
  </object>
  <object>
    <id>5</id>
    <source>TBD</source>
    <type>photo</type>
    <url>http://3.bp.blogspot.com/-X4MTSOjPWXg/T6Nqf6MvcgI/AAAAAAAABHU/GDusB_R3OtM/s1600/mountain+Zebras+babies+of+beautifull+dangerous+animals.jpg</url>
  </object>
  <object>
    <id>6</id>
    <source>TBD</source>
    <type>photo</type>
    <url>http://eofdreams.com/data_images/dreams/tiger/tiger-02.jpg</url>
  </object>
  <object>
    <id>7</id>
    <source>TBD</source>
    <type>photo</type>
    <url>http://images.nationalgeographic.com/wpf/media-live/photos/000/004/cache/african-lion-male_436_600x450.jpg</url>
  </object>
  <object>
    <id>8</id>
    <source>TBD</source>
    <type>photo</type>
    <url>http://images.nationalgeographic.com/wpf/media-live/photos/000/006/cache/leopard_606_600x450.jpg</url>
  </object>
  <object>
    <id>9</id>
    <source>TBD</source>
    <type>photo</type>
    <url>http://www.dartfrogforums.com/images/tinc_540x350_1.jpg</url>
  </object>
  <object>
    <id>10</id>
    <source>TBD</source>
    <type>pdf</type>
    <url>http://www.tldp.org/LDP/intro-linux/intro-linux.pdf</url>
    <tag>computers</tag>
  </object>
  <object>
    <id>11</id>
    <source>TBD</source>
    <type>pdf</type>
    <url>http://linux-training.be/files/books/LinuxFun.pdf</url>
    <tag>linux</tag>
  </object>
  <user>
    <login>tom.cruise@gmail.com</login>
    <email>tom.cruise@gmail.com</email>
    <givenname>Tom</givenname>
    <surname>Cruise</surname>
    <affiliation>Hollywood Actor</affiliation>
    <birthday>1990-12-12</birthday>
    <interests>Baseball</interests>
    <interests>Basketball</interests>
    <interests>Hockey</interests>
    <friend>bill.gates@gmail.com</friend>
    <board>
      <name>Hello World</name>
    </board>
    <board>
      <name>Hello America</name>
    </board>
    <board>
      <name>New Delhi</name>
    </board>
    <pin>
      <objectId>1</objectId>
      <sourceId>TBD</sourceId>
      <board>New Delhi</board>
    </pin>
    <rating>
      <objectId>1</objectId>
      <sourceId>TBD</sourceId>
      <rating>5</rating>
    </rating>
  </user>
  <user>
    <login>amitabh.bacchan@gmail.com</login>
    <email>amitabh.bacchan@gmail.com</email>
    <givenname>Amitabh </givenname>
    <surname>Bacchan</surname>
    <affiliation>Bollywood Actor</affiliation>
    <birthday>1990-12-12</birthday>
    <interests>Baseball</interests>
    <friend>tom.cruise@gmail.com</friend>
    <board>
      <name>Hello World</name>
    </board>
    <pin>
      <objectId>2</objectId>
      <sourceId>TBD</sourceId>
      <board>Hello World</board>
    </pin>
  </user>
  <user>
    <login>arvind.kejriwal@gmail.com</login>
    <email>arvind.kejriwal@gmail.com</email>
    <givenname>Arvind</givenname>
    <surname>Kejriwal</surname>
    <affiliation>Indian Politician</affiliation>
    <birthday>1990-12-12</birthday>
    <friend>manmohan.singh@gmail.com</friend>
    <board>
      <name>Indian Outlook</name>
    </board>
    <pin>
      <objectId>3</objectId>
      <sourceId>TBD</sourceId>
      <board>Indian Outlook</board>
    </pin>
  </user>
  <user>
    <login>stephen.fry@gmail.com</login>
    <email>stephen.fry@gmail.com</email>
    <givenname>Stephen</givenname>
    <surname>Fry</surname>
    <affiliation>British Presenter</affiliation>
    <birthday>1990-12-12</birthday>
    <friend>sachin.tendulkar@gmail.com</friend>
    <board>
      <name>Industrial Revolution</name>
    </board>
    <pin>
      <objectId>4</objectId>
      <sourceId>TBD</sourceId>
      <board>Industrial Revolution</board>
    </pin>
    <rating>
      <objectId>2</objectId>
      <sourceId>TBD</sourceId>
      <rating>5</rating>
    </rating>
    <rating>
      <objectId>3</objectId>
      <sourceId>TBD</sourceId>
      <rating>1</rating>
    </rating>
  </user>
  <user>
    <login>shahrukh.khan@gmail.com</login>
    <email>shahrukh.khan@gmail.com</email>
    <givenname>Shahrukh</givenname>
    <surname>Khan</surname>
    <affiliation>Bollywood Actor</affiliation>
    <birthday>1990-12-12</birthday>
    <board>
      <name>Philadelphia</name>
    </board>
  </user>
  <user>
    <login>jennifer.lawrence@gmail.com</login>
    <email>jennifer.lawrence@gmail.com</email>
    <givenname>Jennifer</givenname>
    <surname>Lawrence</surname>
    <affiliation>Hollywood Actor</affiliation>
    <birthday>1990-12-12</birthday>
    <board>
      <name>New York</name>
    </board>
    <pin>
      <objectId>4</objectId>
      <sourceId>TBD</sourceId>
      <board>New York</board>
    </pin>
  </user>
  <user>
    <login>zach.ives@gmail.com</login>
    <email>zach.ives@gmail.com</email>
    <givenname>Zach</givenname>
    <surname>Ives</surname>
    <affiliation>UPenn Professor</affiliation>
    <birthday>1990-12-12</birthday>
    <friend>bill.gates@gmail.com</friend>
    <board>
      <name>The American Dream</name>
    </board>
    <rating>
      <objectId>7</objectId>
      <sourceId>TBD</sourceId>
      <rating>2</rating>
    </rating>
  </user>
  <user>
    <login>charlie.chaplin@gmail.com</login>
    <email>charlie.chaplin@gmail.com</email>
    <givenname>Charlie </givenname>
    <surname>Chaplin</surname>
    <affiliation>Comedian</affiliation>
    <birthday>1990-12-12</birthday>
    <interests>Computers</interests>
    <friend>bill.gates@gmail.com</friend>
    <board>
      <name>Computer Technology</name>
    </board>
    <board>
      <name>Change the World</name>
    </board>
    <board>
      <name>World Today</name>
    </board>
  </user>
  <user>
    <login>george.bush@gmail.com</login>
    <email>george.bush@gmail.com</email>
    <givenname>George</givenname>
    <surname>Bush</surname>
    <affiliation>US Politician</affiliation>
    <birthday>1990-12-12</birthday>
    <board>
      <name>Economics</name>
    </board>
  </user>
  <user>
    <login>jason.statham@gmail.com</login>
    <email>jason.statham@gmail.com</email>
    <givenname>Jason</givenname>
    <surname>Statham</surname>
    <affiliation>Hollywood Actor</affiliation>
    <birthday>1990-12-12</birthday>
    <board>
      <name>Facebook</name>
    </board>
    <rating>
      <objectId>10</objectId>
      <sourceId>TBD</sourceId>
      <rating>4</rating>
    </rating>
  </user>
  <user>
    <login>sachin.tendulkar@gmail.com</login>
    <email>sachin.tendulkar@gmail.com</email>
    <givenname>Sachin</givenname>
    <surname>Tendular</surname>
    <affiliation>Indian Cricketer</affiliation>
    <birthday>1990-12-12</birthday>
    <board>
      <name>Amazon Shopping</name>
    </board>
    <rating>
      <objectId>6</objectId>
      <sourceId>TBD</sourceId>
      <rating>2</rating>
    </rating>
  </user>
  <user>
    <login>bill.gates@gmail.com</login>
    <email>bill.gates@gmail.com</email>
    <givenname>Bill</givenname>
    <surname>Gates</surname>
    <affiliation>Programming Whiz</affiliation>
    <birthday>1990-12-12</birthday>
    <interests>Phones</interests>
    <board>
      <name>Programming 101</name>
    </board>
    <board>
      <name>Google Hangouts</name>
    </board>
    <rating>
      <objectId>4</objectId>
      <sourceId>TBD</sourceId>
      <rating>1</rating>
    </rating>
  </user>
  <user>
    <login>manmohan.singh@gmail.com</login>
    <email>manmohan.singh@gmail.com</email>
    <givenname>Manmohan</givenname>
    <surname>Singh</surname>
    <affiliation>Indian Politician</affiliation>
    <birthday>1990-12-12</birthday>
    <board>
      <name>Ebay</name>
    </board>
  </user>
</pennterest>
